version: '3'
services:
  chrome:
    image: seleniarm/standalone-chromium:117.0
    environment:
      - SE_NODE_SESSION_TIMEOUT=1800
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 15s
      timeout: 30s
      retries: 5
  robot:
    build: .
    volumes:
      - ./output:/test/output
    environment:
      - GRID=chrome
      - BROWSER
      - REMOTE_BROWSER_URL=http://chrome:4444/wd/hub
      - SERVER
